### ISSUE TITLE
Add Outdoor Experiences

### ISSUE THREAD

**Issue by YadnikaDabhade** [YadnikaDabhade/Travel-WorldWeb#1]
In this section you can add the out door Facinating experiences you enjoyed .the images you captured with the beautiful nature the feelings you want to share .

**Comment by Riya14-dangra** [comment]
> In this section you can add the out door Facinating experiences you enjoyed .the images you captured with the beautiful nature the feelings you want to share .

@YadnikaDabhade can you please assign this issue to me I want to work on it under kwoc2022

**Comment by YadnikaDabhade** [comment]
> > In this section you can add the out door Facinating experiences you enjoyed .the images you captured with the beautiful nature the feelings you want to share .
> 
> @YadnikaDabhade can you please assign this issue to me I want to work on it under kwoc2022

@Riya14-dangra  sure you can go for it
