### ISSUE TITLE
update readme file

### ISSUE THREAD

**Issue by Janhvi52** [YadnikaDabhade/Travel-WorldWeb#10]
hey can i work on this?

**Comment by YadnikaDabhade** [comment]
> hey can i work on this?

@Janhvi52  first complete your remaining tasks , then go for the next , allready you have assigned with lot tasks

**Comment by chandakanup** [comment]
hey @YadnikaDabhade can I work on this?

**Comment by YadnikaDabhade** [comment]
> hey @YadnikaDabhade can I work on this?

@chandakanup Ya sure you can go for it

**Comment by SattyamSamania** [comment]
@YadnikaDabhade Can I work on this?

**Comment by YadnikaDabhade** [comment]
> > hey @YadnikaDabhade can I work on this?
> 
> @chandakanup Ya sure you can go for it

Complete the task as early as possible

**Comment by anup-chandak** [comment]
@YadnikaDabhade you can assign this issue to @SattyamSamania.

**Comment by Janhvi52** [comment]
> > hey can i work on this?
> 
> @Janhvi52 first complete your remaining tasks , then go for the next , allready you have assigned with lot tasks

can i work on it now?

**Comment by YadnikaDabhade** [comment]
> @YadnikaDabhade Can I work on this?

@SattyamSamania  go for it
