### ISSUE TITLE
Blog Page 

### ISSUE THREAD

**Issue by himanshu1221** [YadnikaDabhade/Travel-WorldWeb#12]
I want to work on the blog page can you please assign it to me under KWoC22 label 
.
i'll make a responsie page along with working home and blog button on navbar

**Comment by himanshu1221** [comment]
@YadnikaDabhade  please assign this to me so i can make a pr and  please dont forget to add **KWoC22 label**

**Comment by YadnikaDabhade** [comment]
> @YadnikaDabhade please assign this to me so i can make a pr and please dont forget to add **KWoC22 label**
@himanshu1221  Sure go for it.

**Comment by himanshu1221** [comment]
@YadnikaDabhade you can close this issue with a KWoC22 label
