### ISSUE TITLE
Add Featured Tour Packages

### ISSUE THREAD

**Issue by YadnikaDabhade** [YadnikaDabhade/Travel-WorldWeb#2]
In this section you can add the Popular Packages of the tour like by specifying the place image and the cost of it with regarding information so that can will help full to the travelers to enjoy the Tour.

**Comment by Riya14-dangra** [comment]
> In this section you can add the Popular Packages of the tour like by specifying the place image and the cost of it with regarding information so that can will help full to the travelers to enjoy the Tour.

@YadnikaDabhade can you please assign this issue to me I want to work on it under kwoc2022

**Comment by YadnikaDabhade** [comment]
> > In this section you can add the Popular Packages of the tour like by specifying the place image and the cost of it with regarding information so that can will help full to the travelers to enjoy the Tour.
> 
> @YadnikaDabhade can you please assign this issue to me I want to work on it under kwoc2022

@Riya14-dangra  , Ya sure go for it..
