### ISSUE TITLE
add a search bar for booking

### ISSUE THREAD

**Issue by ArgyPorgy** [YadnikaDabhade/Travel-WorldWeb#21]
it will contain destination, date, budget and a search button

**Comment by ArgyPorgy** [comment]
can you please assign this to me under kwoc2022? @YadnikaDabhade

**Comment by SomilRathore01** [comment]
Hey! @YadnikaDabhade can you please assign this project to me for competing in KWOC 2022.

**Comment by YadnikaDabhade** [comment]
> can you please assign this to me under kwoc2022? @YadnikaDabhade

@ArgyPorgy  go for it..
