### ISSUE TITLE
Add Feature Products & what they offer

### ISSUE THREAD

**Issue by YadnikaDabhade** [YadnikaDabhade/Travel-WorldWeb#3]
As it is travel World Website ,so  in Feature Products you can add the things link their Survival kit in which their is Bag, Shoes and many more things as such important while travelling with their images and cost of that product. Also in their Offer you can add The tour Guide ,Family Trip , Adventure Trail , Various adventures places with some information .

**Comment by Riya14-dangra** [comment]
> As it is travel World Website ,so in Feature Products you can add the things link their Survival kit in which their is Bag, Shoes and many more things as such important while travelling with their images and cost of that product. Also in their Offer you can add The tour Guide ,Family Trip , Adventure Trail , Various adventures places with some information .

@YadnikaDabhade can you please assign this issue to me I want to work on it under kwoc2022

**Comment by YadnikaDabhade** [comment]
> > As it is travel World Website ,so in Feature Products you can add the things link their Survival kit in which their is Bag, Shoes and many more things as such important while travelling with their images and cost of that product. Also in their Offer you can add The tour Guide ,Family Trip , Adventure Trail , Various adventures places with some information .
> 
> @YadnikaDabhade can you please assign this issue to me I want to work on it under kwoc2022

@Riya14-dangra  Sure you can go for it
