### ISSUE TITLE
add a footer section

### ISSUE THREAD

**Issue by Janhvi52** [YadnikaDabhade/Travel-WorldWeb#7]

**Comment by abantika27** [comment]
can you please assign this issue to me?

**Comment by YadnikaDabhade** [comment]
@Janhvi52   sure , go for it

**Comment by abantika27** [comment]
Can this be assigned to me as well?

**Comment by YadnikaDabhade** [comment]
> Can this be assigned to me as well?

@abantika27  No ,it is already assigned
